DROP TABLE IF EXISTS admin;
CREATE TABLE admin (
  id int(20) unsigned NOT NULL AUTO_INCREMENT,
  username VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL DEFAULT '',
  mobile VARCHAR(100) NOT NULL DEFAULT '',
  status tinyint(1) NOT NULL DEFAULT 0 COMMENT '0:disabled;1:enabled',
  create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(ID)
);
CREATE UNIQUE INDEX index_admin_username ON admin (username);

DROP TABLE if exists product_raw;
CREATE TABLE product_raw (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  affiliate VARCHAR(100) NOT NULL DEFAULT 'www',
  status TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0:pending;1:ready;2:remove',
  weight INT UNSIGNED NOT NULL DEFAULT 0,
  create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  # from excel:
  tid BIGINT NOT NULL DEFAULT 0,
  title VARCHAR(500) NOT NULL DEFAULT '',
  thumb VARCHAR(1000) NOT NULL DEFAULT '',
  detailUrl VARCHAR(1000) NOT NULL DEFAULT '',
  store VARCHAR(100) NOT NULL DEFAULT '',
  price INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '人民币分',
  saleVolume INT UNSIGNED NOT NULL DEFAULT 0,
  commissionRate TINYINT(2) UNSIGNED NOT NULL DEFAULT 0 COMMENT '百分数值:1代表1%',
  commissionValue INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '人民币分',
  sellerWaWa VARCHAR(100) NOT NULL DEFAULT '',
  tkShortUrl VARCHAR(100) NOT NULL DEFAULT '',
  tkUrl VARCHAR(1000) NOT NULL DEFAULT '',
  tkCode VARCHAR(100) NOT NULL DEFAULT '',
  couponTotal INT UNSIGNED NOT NULL DEFAULT 0,
  couponAvailable INT UNSIGNED NOT NULL DEFAULT 0,
  couponValue VARCHAR(100) NOT NULL DEFAULT '',
  couponStart TIMESTAMP NOT NULL DEFAULT '2018-01-01',
  couponEnd  TIMESTAMP NOT NULL DEFAULT '2018-01-01',
  couponUrl VARCHAR(1000) NOT NULL DEFAULT '',
  couponCode VARCHAR(100) NOT NULL DEFAULT '',
  couponShortUrl VARCHAR(100) NOT NULL DEFAULT '',
  isRecommend TINYINT(1) NOT NULL DEFAULT 0,
  groupThresh INT UNSIGNED NOT NULL DEFAULT 0,
  groupPrice INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '人民币分',
  groupCommission INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '人民币分',
  groupStart TIMESTAMP NOT NULL DEFAULT '2018-01-01',
  groupEnd TIMESTAMP NOT NULL DEFAULT '2018-01-01'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX index_product_affiliate ON product_raw (affiliate);
CREATE UNIQUE INDEX index_product_affiliate_pid ON product_raw (affiliate, tid);
